name: Build and deploy

on:
  push:
    branches: [ master ]
  issue_comment:
    types: [ created, edited ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
       npm install
       CI=false npm run build

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.0.0
      with:
        build_dir: build
